package storage

import "strings"

// SchemaVersion — версия схемы модуля (docs/plan/02-database.md §5): любое
// изменение DDL ниже — с инкрементом этой константы; несовпадение с
// schema_meta.schema_version — отказ в работе (schema_version_mismatch),
// миграций нет (D5). Версия 2 — каталожные таблицы без текстовых колонок
// (D9: отображаемые строки — бандлы internal/i18n; коды единиц — латиница).
// Версия 3 — словарь материалов полупроводников (коды вместо русских
// названий в device_designation_fields.text_value). Версия 4 — словарь
// подклассов и способов подстройки (коды полей subclass/adjustment),
// классификационные поля секции fields и каталожный словарь категорий.
const SchemaVersion = 4

// autoIncToken — маркер авто-PK в переносимом DDL; диалект заменяет его
// своим определением (sqlite: PRIMARY KEY AUTOINCREMENT — запрет
// переиспользования id; postgres: GENERATED BY DEFAULT AS IDENTITY).
const autoIncToken = "{{AUTOINC}}"

// ddlStatements — полный переносимый DDL (CREATE … IF NOT EXISTS) по
// docs/plan/02-database.md §2. Порядок учитывает FK (сначала ссылки, потом
// ссылающиеся). Типы — INTEGER/REAL/TEXT; булевы — INTEGER 0/1; «не задано»
// — NULL; CHECK только структурный (каталог — данные, DDL его не знает).
var ddlStatements = []string{
	`CREATE TABLE IF NOT EXISTS schema_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
)`,

	`CREATE TABLE IF NOT EXISTS kinds (
    code TEXT PRIMARY KEY
)`,

	`CREATE TABLE IF NOT EXISTS designation_systems (
    code TEXT PRIMARY KEY
)`,

	`CREATE TABLE IF NOT EXISTS designation_system_kinds (
    system_code TEXT NOT NULL REFERENCES designation_systems(code) ON DELETE CASCADE,
    kind_code   TEXT NOT NULL REFERENCES kinds(code) ON DELETE CASCADE,
    PRIMARY KEY (system_code, kind_code)
)`,

	`CREATE TABLE IF NOT EXISTS series_families (
    series        TEXT NOT NULL,
    kind_code     TEXT NOT NULL REFERENCES kinds(code),
    tail_semantic TEXT NULL,
    PRIMARY KEY (series, kind_code)
)`,

	`CREATE TABLE IF NOT EXISTS units (
    code TEXT PRIMARY KEY
)`,

	`CREATE TABLE IF NOT EXISTS categories (
    code TEXT PRIMARY KEY
)`,

	`CREATE TABLE IF NOT EXISTS conditions (
    code           TEXT PRIMARY KEY,
    unit_code      TEXT NULL REFERENCES units(code),
    allow_negative INTEGER NOT NULL DEFAULT 0
)`,

	`CREATE TABLE IF NOT EXISTS parameter_groups (
    code         TEXT PRIMARY KEY,
    section_name TEXT NOT NULL,
    sort_order   INTEGER NOT NULL
)`,

	`CREATE TABLE IF NOT EXISTS validation_rules (
    code TEXT PRIMARY KEY
)`,

	`CREATE TABLE IF NOT EXISTS parameters (
    code            TEXT PRIMARY KEY,
    group_code      TEXT NOT NULL REFERENCES parameter_groups(code),
    unit_code       TEXT NULL REFERENCES units(code),
    value_type      TEXT NOT NULL,
    value_ceiling   REAL NULL,
    allow_negative  INTEGER NOT NULL DEFAULT 0,
    validation_rule TEXT NULL REFERENCES validation_rules(code),
    sort_order      INTEGER NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 1
)`,

	`CREATE TABLE IF NOT EXISTS parameter_kinds (
    parameter_code TEXT NOT NULL REFERENCES parameters(code) ON DELETE CASCADE,
    kind_code      TEXT NOT NULL REFERENCES kinds(code) ON DELETE CASCADE,
    PRIMARY KEY (parameter_code, kind_code)
)`,

	`CREATE TABLE IF NOT EXISTS parameter_enum_values (
    parameter_code TEXT NOT NULL REFERENCES parameters(code) ON DELETE CASCADE,
    value          TEXT NOT NULL,
    PRIMARY KEY (parameter_code, value)
)`,

	`CREATE TABLE IF NOT EXISTS parameter_condition_sets (
    parameter_code TEXT NOT NULL REFERENCES parameters(code) ON DELETE CASCADE,
    set_no         INTEGER NOT NULL,
    PRIMARY KEY (parameter_code, set_no)
)`,

	`CREATE TABLE IF NOT EXISTS parameter_condition_set_items (
    parameter_code TEXT NOT NULL,
    set_no         INTEGER NOT NULL,
    condition_code TEXT NOT NULL REFERENCES conditions(code),
    mode           TEXT NOT NULL,
    fixed_value    REAL NULL,
    PRIMARY KEY (parameter_code, set_no, condition_code),
    FOREIGN KEY (parameter_code, set_no)
        REFERENCES parameter_condition_sets(parameter_code, set_no)
        ON DELETE CASCADE
)`,

	`CREATE TABLE IF NOT EXISTS attributes (
    code            TEXT PRIMARY KEY,
    "group"         TEXT NULL,
    value_type      TEXT NOT NULL,
    unit_code       TEXT NULL REFERENCES units(code),
    validation_rule TEXT NULL REFERENCES validation_rules(code),
    sort_order      INTEGER NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 1
)`,

	`CREATE TABLE IF NOT EXISTS attribute_kinds (
    attribute_code TEXT NOT NULL REFERENCES attributes(code) ON DELETE CASCADE,
    kind_code      TEXT NOT NULL REFERENCES kinds(code) ON DELETE CASCADE,
    PRIMARY KEY (attribute_code, kind_code)
)`,

	`CREATE TABLE IF NOT EXISTS attribute_enum_values (
    attribute_code TEXT NOT NULL REFERENCES attributes(code) ON DELETE CASCADE,
    value          TEXT NOT NULL,
    PRIMARY KEY (attribute_code, value)
)`,

	`CREATE TABLE IF NOT EXISTS kind_validation_rules (
    kind_code       TEXT NOT NULL REFERENCES kinds(code) ON DELETE CASCADE,
    validation_rule TEXT NOT NULL REFERENCES validation_rules(code) ON DELETE CASCADE,
    PRIMARY KEY (kind_code, validation_rule)
)`,

	`CREATE TABLE IF NOT EXISTS devices (
    id           INTEGER ` + autoIncToken + `,
    kind_code    TEXT NOT NULL REFERENCES kinds(code),
    system_code  TEXT NOT NULL REFERENCES designation_systems(code),
    designation  TEXT NOT NULL,
    UNIQUE (kind_code, designation)
)`,

	`CREATE TABLE IF NOT EXISTS device_designation_fields (
    device_id  INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    field      TEXT NOT NULL,
    text_value TEXT NULL,
    num_value  REAL NULL,
    PRIMARY KEY (device_id, field)
)`,

	`CREATE TABLE IF NOT EXISTS device_attribute_values (
    device_id      INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    attribute_code TEXT NOT NULL REFERENCES attributes(code),
    text_value     TEXT NULL,
    num_value      REAL NULL,
    bool_value     INTEGER NULL,
    PRIMARY KEY (device_id, attribute_code),
    CHECK (bool_value IS NULL OR bool_value IN (0, 1))
)`,

	`CREATE TABLE IF NOT EXISTS device_variants (
    id         INTEGER ` + autoIncToken + `,
    device_id  INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    label      TEXT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
)`,

	`CREATE TABLE IF NOT EXISTS parameter_values (
    id             INTEGER ` + autoIncToken + `,
    device_id      INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    variant_id     INTEGER NULL REFERENCES device_variants(id) ON DELETE CASCADE,
    parameter_code TEXT NOT NULL REFERENCES parameters(code),
    value_exact    REAL NULL,
    value_min      REAL NULL,
    value_max      REAL NULL,
    value_text     TEXT NULL,
    sort_order     INTEGER NOT NULL DEFAULT 0
)`,

	`CREATE TABLE IF NOT EXISTS parameter_value_conditions (
    parameter_value_id INTEGER NOT NULL REFERENCES parameter_values(id) ON DELETE CASCADE,
    condition_code     TEXT NOT NULL REFERENCES conditions(code),
    value              REAL NOT NULL,
    PRIMARY KEY (parameter_value_id, condition_code)
)`,

	`CREATE TABLE IF NOT EXISTS manufacturers (
    id   INTEGER ` + autoIncToken + `,
    name TEXT NOT NULL UNIQUE
)`,

	`CREATE TABLE IF NOT EXISTS device_manufacturers (
    device_id       INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    manufacturer_id INTEGER NOT NULL REFERENCES manufacturers(id) ON DELETE CASCADE,
    PRIMARY KEY (device_id, manufacturer_id)
)`,

	`CREATE TABLE IF NOT EXISTS device_analogs (
    device_id       INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    analog_device_id INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    note            TEXT NULL,
    PRIMARY KEY (device_id, analog_device_id),
    CHECK (device_id <> analog_device_id)
)`,

	// Индексы — docs/plan/02-database.md §3.
	`CREATE INDEX IF NOT EXISTS idx_devices_system ON devices(system_code)`,

	`CREATE INDEX IF NOT EXISTS idx_ddf_field_text ON device_designation_fields(field, text_value)`,
	`CREATE INDEX IF NOT EXISTS idx_ddf_field_num ON device_designation_fields(field, num_value)`,

	`CREATE INDEX IF NOT EXISTS idx_dav_attr_text ON device_attribute_values(attribute_code, text_value)`,
	`CREATE INDEX IF NOT EXISTS idx_dav_attr_num ON device_attribute_values(attribute_code, num_value)`,

	`CREATE INDEX IF NOT EXISTS idx_pv_code_min ON parameter_values(parameter_code, value_min)`,
	`CREATE INDEX IF NOT EXISTS idx_pv_code_max ON parameter_values(parameter_code, value_max)`,
	`CREATE INDEX IF NOT EXISTS idx_pv_code_exact ON parameter_values(parameter_code, value_exact)`,
	`CREATE INDEX IF NOT EXISTS idx_pv_code_text ON parameter_values(parameter_code, value_text)`,
	`CREATE INDEX IF NOT EXISTS idx_pv_device ON parameter_values(device_id)`,
	`CREATE INDEX IF NOT EXISTS idx_pv_variant ON parameter_values(variant_id)`,

	`CREATE INDEX IF NOT EXISTS idx_dv_device ON device_variants(device_id)`,

	`CREATE INDEX IF NOT EXISTS idx_analogs_analog ON device_analogs(analog_device_id)`,
}

// ddlFor возвращает DDL с подставленным определением авто-PK диалекта.
func ddlFor(d Dialect) []string {
	out := make([]string, len(ddlStatements))
	for i, s := range ddlStatements {
		out[i] = strings.ReplaceAll(s, autoIncToken, d.AutoIncSQL())
	}
	return out
}

// TableNames — имена каталожных таблиц модуля, выведенные из DDL
// (ddlStatements): единый источник для очистки одноразовых баз —
// qa/runner использует напрямую, internal/testutil — копией,
// синхронизированной пин-тестом (импорт storage в testutil запрещён:
// тесты storage импортируют testutil). DROP — с CASCADE, порядок не важен.
func TableNames() []string {
	const prefix = "CREATE TABLE IF NOT EXISTS "
	out := make([]string, 0, len(ddlStatements))
	for _, s := range ddlStatements {
		if !strings.HasPrefix(s, prefix) {
			continue
		}
		name := strings.TrimPrefix(s, prefix)
		if i := strings.IndexByte(name, ' '); i >= 0 {
			name = name[:i]
		}
		out = append(out, name)
	}
	return out
}
