package storage

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // драйвер регистрируется как "pgx"
)

// postgresDialect — диалект PostgreSQL (pgx/v5 в режиме stdlib): единый пул
// соединений для чтения и записи (план 02 §4); параметры пула — из
// конфигурации.
type postgresDialect struct{}

func (postgresDialect) Name() string { return "postgres" }

// RewriteDDL подставляет авто-PK и точные типы: INTEGER → BIGINT —
// диапазон int64 у id и ссылок совпадает со sqlite, входные значения вне
// int4 (REST/поиск по id) не отбрасываются кодированием параметров;
// REAL → DOUBLE PRECISION — sqlite REAL хранит float64, postgres REAL —
// float4 (бит-точное сравнение состояний повторного импорта расползалось
// бы на четвёртом знаке).
func (postgresDialect) RewriteDDL(stmt string) string {
	return strings.NewReplacer(
		"INTEGER", "BIGINT",
		"REAL", "DOUBLE PRECISION",
		autoIncToken, "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
	).Replace(stmt)
}

func (postgresDialect) InsertReturningID(ctx context.Context, tx *sql.Tx, query string, args []any) (int64, error) {
	var id int64
	if err := tx.QueryRowContext(ctx, query+" RETURNING id", args...).Scan(&id); err != nil {
		return 0, err
	}
	return id, nil
}

func (postgresDialect) InsertIfAbsentReturningID(ctx context.Context, tx *sql.Tx, query string, args []any) (int64, bool, error) {
	var id int64
	err := tx.QueryRowContext(ctx, query+" ON CONFLICT DO NOTHING RETURNING id", args...).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	return id, true, nil
}

// appendDSNParam дописывает параметр к DSN в его форме: URL
// (postgres://…) — в строку запроса, ключевая (host=… port=…) — через
// пробел. pgx передаёт неизвестные ему параметры серверу в стартовом
// пакете — значение действует на каждое соединение пула без
// дополнительного round-trip.
func appendDSNParam(dsn, param string) string {
	if strings.Contains(dsn, "://") {
		sep := "?"
		if strings.Contains(dsn, "?") {
			sep = "&"
		}
		return dsn + sep + param
	}
	return dsn + " " + param
}

// withJitDisabled дописывает к DSN runtime-параметр jit=off, если jit
// не задан явно (docs/plan/02-database.md §4). Нагрузка модуля — короткие
// точечные запросы; оценка стоимости плана параметрического поиска,
// раздутая коррелированными EXISTS вариантной семантики, переваливает за
// jit_threshold (100 тыс.), и LLVM-компиляция стоит на слабых CPU сотни
// мс при десятках мс выполнения (измерения — qa/reports). Явный jit= в
// DSN не перекрывается.
func withJitDisabled(dsn string) string {
	if strings.Contains(dsn, "jit=") {
		return dsn
	}
	return appendDSNParam(dsn, "jit=off")
}

func (postgresDialect) Open(ctx context.Context, cfg Config) (*pools, error) {
	db, err := sql.Open("pgx", withJitDisabled(cfg.DSN))
	if err != nil {
		return nil, err
	}
	if cfg.Pool.MaxOpen > 0 {
		db.SetMaxOpenConns(cfg.Pool.MaxOpen)
	}
	if cfg.Pool.MaxIdle > 0 {
		db.SetMaxIdleConns(cfg.Pool.MaxIdle)
	}
	if cfg.Pool.ConnMaxLifetime > 0 {
		db.SetConnMaxLifetime(durationOf(cfg.Pool.ConnMaxLifetime))
	}
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, err
	}
	return &pools{reads: db, writes: db, same: true}, nil
}

func durationOf(ns int64) time.Duration { return time.Duration(ns) * time.Nanosecond }
