package storage

import (
	"context"
	"database/sql"
	"errors"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib" // драйвер регистрируется как "pgx"
)

// postgresDialect — диалект PostgreSQL (pgx/v5 в режиме stdlib): единый пул
// соединений для чтения и записи (план 02 §4); параметры пула — из
// конфигурации.
type postgresDialect struct{}

func (postgresDialect) Name() string { return "postgres" }

func (postgresDialect) AutoIncSQL() string {
	return "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

func (postgresDialect) InsertReturningID(ctx context.Context, tx *sql.Tx, query string, args []any) (int64, error) {
	var id int64
	if err := tx.QueryRowContext(ctx, query+" RETURNING id", args...).Scan(&id); err != nil {
		return 0, err
	}
	return id, nil
}

func (postgresDialect) InsertIfAbsentReturningID(ctx context.Context, tx *sql.Tx, query string, args []any) (int64, bool, error) {
	var id int64
	err := tx.QueryRowContext(ctx, query+" ON CONFLICT DO NOTHING RETURNING id", args...).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, err
	}
	return id, true, nil
}

func (postgresDialect) Open(ctx context.Context, cfg Config) (*pools, error) {
	db, err := sql.Open("pgx", cfg.DSN)
	if err != nil {
		return nil, err
	}
	if cfg.Pool.MaxOpen > 0 {
		db.SetMaxOpenConns(cfg.Pool.MaxOpen)
	}
	if cfg.Pool.MaxIdle > 0 {
		db.SetMaxIdleConns(cfg.Pool.MaxIdle)
	}
	if cfg.Pool.ConnMaxLifetime > 0 {
		db.SetConnMaxLifetime(durationOf(cfg.Pool.ConnMaxLifetime))
	}
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, err
	}
	return &pools{reads: db, writes: db, same: true}, nil
}

func durationOf(ns int64) time.Duration { return time.Duration(ns) * time.Nanosecond }
